name: flutter_beginning
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/130.jpg
    - assets/images/doctor.jpg
    - assets/images/shape.jpg
    - assets/images/Illustration.jpg
    - assets/images/Hello.jpg
    - assets/images/Back.jpg
    - assets/images/del.jpg
